name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x' # Replace with your .NET version

      - name: Install dependencies
        run: dotnet restore src/HelloWorldApp.csproj

      - name: Build
        run: dotnet build src/HelloWorldApp.csproj --no-restore

      - name: Test
        run: dotnet test src/HelloWorldApp.csproj --no-build --verbosity normal

      - name: Code Coverage
        run: dotnet test src/HelloWorldApp.csproj --collect:"XPlat Code Coverage"

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3
        with:
          file: coverage.cobertura.xml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Staging
        run: echo "Deploy stage - Add your deploy commands here"

  notify:
    runs-on: ubuntu-latest
    needs: [build, deploy]
    if: failure()
    steps:
      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
